apiVersion: v1
kind: Template
metadata:
  name: "anchore-engine-scc"
  annotation:
    openshift.io/display-name: "Anchore-engine Security Context Constraints"
    openshift.io/documentation-url: "https://github.com/anchore/anchore-engine"
objects:
- allowHostDirVolumePlugin: false
  allowHostIPC: false
  allowHostNetwork: false
  allowHostPID: false
  allowHostPorts: false
  allowPrivilegedContainer: false
  allowedCapabilities:
  - '*'
  allowedFlexVolumes: null
  apiVersion: v1
  defaultAddCapabilities: null
  fsGroup:
    type: RunAsAny
  groups:
  - system:cluster-admins
  kind: SecurityContextConstraints
  metadata:
    annotations:
      kubernetes.io/description: anyuid provides all features of the restricted SCC
        but allows users to run with any UID and any GID.
    creationTimestamp: null
    name: anchore-engine
  priority: 15
  readOnlyRootFilesystem: false
  runAsUser:
    type: RunAsAny
  seLinuxContext:
    type: MustRunAs
  supplementalGroups:
    type: RunAsAny
  users:
  - system:serviceaccount:${NAMESPACE}:anchore-engine
  volumes:
  - configMap
  - downwardAPI
  - emptyDir
  - persistentVolumeClaim
  - projected
  - secret

parameters:
- name: NAMESPACE
  displayName: Current namespace
  description: OC namespace to deploy into
  value: edp-cicd-vlg1
